name: horizontal_week_calendar
description: A horizontal week calender with on change week and on date selected function
version: 0.1.0
homepage: https://github.com/chandabdullah/horizontal_week_calendar

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter
  # carousel_slider: ^5.0.0
  carousel_slider_plus: ^7.1.1
  hijri_date: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
